apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.name}}
spec:
  strategy:
    type: Recreate
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      serviceAccountName: {{.Values.serviceAccountName}}
      containers:
        - name: main
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          imagePullPolicy: IfNotPresent
          args:
            - "./main"
            - "-port"
            - {{.Values.service.targetPort | quote }}
            - "-host"
            - "kraken-plugins.duckdns.org"
          ports:
            - containerPort: {{.Values.service.targetPort}}
              name: tcp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
