apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{.Values.name}}-svc
spec:
  type: {{.Values.service.type}}
  selector:
    app: {{.Values.name}}
  ports:
    - port: {{.Values.service.port}}
      protocol: TCP
      name: tcp

